#!/bin/sh

# Module showing network traffic. Shows how much data has been received (RX) or
# transmitted (TX) since the previous time this script ran. So if run every
# second, gives network traffic per second.

case $BUTTON in
	1) setsid -f "$TERMINAL" -e bmon ;;
	3) notify-send "🌐 Network traffic module" "🡻 : Traffic received
🡹 : Traffic transmitted
-----------------------
Speed (bytes/s)
🌵: 0
🐌: 0-1K
🐪: 1K-1M
🐎: 1M - 10M
🦅: 10M - 100M 
🚀: 100M - ..." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

update() {
    sum=0
    for arg; do
        read -r i < "$arg"
        sum=$(( sum + i ))
    done
    cache=/tmp/${1##*/}
    [ -f "$cache" ] && read -r old < "$cache" || old=0
    printf %d\\n "$sum" > "$cache"
    printf %d\\n $(( sum - old ))
}

rx=$(update /sys/class/net/[ew]*/statistics/rx_bytes)
tx=$(update /sys/class/net/[ew]*/statistics/tx_bytes)

get_emoji() {
    if   [ "$1" = 0  ]; then emoji='🌵'
    elif [ "$1" -lt 1024 ]; then emoji='🐌'
    elif [ "$1" -lt 1048576 ]; then emoji='🐪'
    elif [ "$1" -lt 10485760 ]; then emoji='🐎'
    elif [ "$1" -lt 104857600 ]; then emoji='🦅'
    else emoji='🚀'
    fi
    echo "$emoji"
}

printf "🡻%s🡹%s\\n" $(get_emoji $rx) $(get_emoji $tx)
