#!/bin/sh
# AMB docker utils

node_container_name="paybutton-server-paybutton-1"
db_container_name="paybutton-server-db-1"
base_command_node="docker exec  -it $node_container_name"
base_command_db="docker exec -it $db_container_name"
command="$1"

shift
case "$command" in
    "help" | "h" | "-h" | "--help")
        echo Avaiable commands:
        echo "  shortcut, command           [container_name]    command description"
        echo " --- "
        echo "  db, database                [$db_container_name]     enter the mariadb command-line"
        echo "  n, node                     [$node_container_name]   enter the node container"
        echo "  genmigration, gm            [$node_container_name]   create migration file with name ARGS"
        echo "  migrate, mig                [$node_container_name]   run migrations"
        echo "  migrateto, mt               [$node_container_name]   run migrations until ARGS"
        echo "  showmigrations, sm          [$node_container_name]   show migrations"
        echo "  undolast, ul                [$node_container_name]   undo last migration"
        echo "  undoto, ut                  [$node_container_name]   undo to migration ARGS"
        echo "  undoall, ua                 [$node_container_name]   undo all migrations"
        ;;
    "database" | "db")
        eval "$base_command_db" mariadb -u paybutton -ppaybutton "$@"
        ;;
    "node" | "n")
        eval "$base_command_node" ash -l
        ;;
    "genmigration" | "gm")
        eval "$base_command_node" sequelize-cli migration:generate --name "$@"
        ;;
    "migrate" | "mig")
        eval "$base_command_node" sequelize-cli db:migrate
        ;;
    "migrateto" | "mt")
        eval "$base_command_node" sequelize-cli db:migrate --to "$@"
        ;;
    "showmigrations" | "sm")
        eval "$base_command_node" sequelize-cli db:migrate:status
        ;;
    "undolast" | "ul")
        eval "$base_command_node" sequelize-cli db:migrate:undo
        ;;
    "undoto" | "ut")
        eval "$base_command_node" sequelize-cli db:migrate:undo:all --to "$@"
        ;;
    "undoall" | "ua")
        eval "$base_command_node" sequelize-cli db:migrate:undo:all
        ;;
    *)
        eval "$node_container_name" "$command" "$@"
        ;;
esac
