#!/bin/bash

ARG_PATH="$1"
if [[ "$ARG_PATH" == pb ]]
then
    kitty --session ~/.config/kitty/paybutton.session &
    exit
fi


echo "$ARG_PATH"
sed 's|ARG_PATH|'"$ARG_PATH"'|g' ~/.config/kitty/template.session > ~/.config/kitty/temp.session

kitty --session ~/.config/kitty/temp.session &
