#!/bin/bash
# Reset

ESC=$(printf '\033')

COLOR_OFF="${ESC}[0m"       # Text Reset

# Regular Colors
BLACK="${ESC}[0;30m"        # Black
RED="${ESC}[0;31m"          # Red
GREEN="${ESC}[0;32m"        # Green
YELLOW="${ESC}[0;33m"       # Yellow
BLUE="${ESC}[0;34m"         # Blue
PURPLE="${ESC}[0;35m"       # Purple
CYAN="${ESC}[0;36m"         # Cyan
WHITE="${ESC}[0;37m"        # White

# Bold
BBLACK="${ESC}[1;30m"       # Black
BRED="${ESC}[1;31m"         # Red
BGREEN="${ESC}[1;32m"       # Green
BYELLOW="${ESC}[1;33m"      # Yellow
BBLUE="${ESC}[1;34m"        # Blue
BPURPLE="${ESC}[1;35m"      # Purple
BCYAN="${ESC}[1;36m"        # Cyan
BWHITE="${ESC}[1;37m"       # White

# Underline
UBLACK="${ESC}[4;30m"       # Black
URED="${ESC}[4;31m"         # Red
UGREEN="${ESC}[4;32m"       # Green
UYELLOW="${ESC}[4;33m"      # Yellow
UBLUE="${ESC}[4;34m"        # Blue
UPURPLE="${ESC}[4;35m"      # Purple
UCYAN="${ESC}[4;36m"        # Cyan
UWHITE="${ESC}[4;37m"       # White

# Background
ON_BLACK="${ESC}[40m"       # Black
ON_RED="${ESC}[41m"         # Red
ON_GREEN="${ESC}[42m"       # Green
ON_YELLOW="${ESC}[43m"      # Yellow
ON_BLUE="${ESC}[44m"        # Blue
ON_PURPLE="${ESC}[45m"      # Purple
ON_CYAN="${ESC}[46m"        # Cyan
ON_WHITE="${ESC}[47m"       # White

# High Intensity
IBLACK="${ESC}[0;90m"       # Black
IRED="${ESC}[0;91m"         # Red
IGREEN="${ESC}[0;92m"       # Green
IYELLOW="${ESC}[0;93m"      # Yellow
IBLUE="${ESC}[0;94m"        # Blue
IPURPLE="${ESC}[0;95m"      # Purple
ICYAN="${ESC}[0;96m"        # Cyan
IWHITE="${ESC}[0;97m"       # White

# Bold High Intensity
BIBLACK="${ESC}[1;90m"      # Black
BIRED="${ESC}[1;91m"        # Red
BIGREEN="${ESC}[1;92m"      # Green
BIYELLOW="${ESC}[1;93m"     # Yellow
BIBLUE="${ESC}[1;94m"       # Blue
BIPURPLE="${ESC}[1;95m"     # Purple
BICYAN="${ESC}[1;96m"       # Cyan
BIWHITE="${ESC}[1;97m"      # White

# High Intensity backgrounds
ON_IBLACK="${ESC}[0;100m"   # Black
ON_IRED="${ESC}[0;101m"     # Red
ON_IGREEN="${ESC}[0;102m"   # Green
ON_IYELLOW="${ESC}[0;103m"  # Yellow
ON_IBLUE="${ESC}[0;104m"    # Blue
ON_IPURPLE="${ESC}[0;105m"  # Purple
ON_ICYAN="${ESC}[0;106m"    # Cyan
ON_IWHITE="${ESC}[0;107m"   # White
