#!/bin/bash

find_pattern="$1"
sed_pattern="$2"

[[ -z "$find_pattern" ]] && echo "Missing grep pattern" && exit 1
[[ -z "$sed_pattern" ]] && echo "Missing sed pattern" && exit 1

git grep --color=never -lr "$find_pattern"  | xargs sed -i s/"$find_pattern"/"$sed_pattern"/g
