#!/bin/bash

# Set input and output file names
input_file="/tmp/hosts"
output_file="$1"

echo oia 1 $1 2 $2 3 $3
[[ -z "$output_file" ]] && echo "Missing argument" && exit

# Loop through each line of the input file
output_1="$(mktemp)"
echo vai pra $output_1
output_2="$(mktemp)"
while read line; do
    if [[ "$line" == "#"* ]]; then
        continue
    fi

    # Check if the line contains "www."
    if [[ "$line" =~ 0.0.0.0[[:space:]]+www\. ]]; then
        echo "$line" >> "$output_1" # If it does, append it to the output file
        echo "${line/ www./ }" >> "$output_1" # and the same line without
    else
        # If it doesn't, append the original line and a corresponding line with "www." added to the output file
        echo "$line" >> "$output_1"
        # echo "${line/ (\w)/ www.\1}" >> "$output_1"
        #echo "${line/ [[:alnum:]]/ www.}" >> "$output_1"
        echo "$line" | sed 's/ \(\w\)/ www.\1/' >> "$output_1"
    fi

done < "$input_file"

sort "$output_1" > "$output_2"
uniq "$output_2" > "$output_file"
