#!/bin/bash

DAY=$(date +%d)
MONTH=$(date +%m)
YEAR=$(date +%y)

key="$1"
JOURNAL_DIR="/home/$USER/documents/journal"

case $key in
    -r|--read)
        (cd "$JOURNAL_DIR" && for file in *; do echo "$file" ; echo ----- ; echo ; cat "$JOURNAL_DIR"/"$file" ; echo ; done| $EDITOR -R -c 'set ft=markdown' -)
        ;;
    *)
        (cd "$JOURNAL_DIR" && $EDITOR "$YEAR"-"$MONTH"-"$DAY".md -S .jrnl.vim)
        ;;
esac
