#!/bin/bash

function reset_nm {
    echo "$(date '+%Y-%m-%d %H:%M:%S')" Reconnecting...
    nmcli networking off
    sleep 1
    nmcli networking on
    echo "$(date '+%Y-%m-%d %H:%M:%S')" Networking on again...
}

function wait_until_on {
    ret=0
    while true; do
        sleep 1
        ping -c 3 -i 0.2 -W 2 archlinux.org &> /dev/null && ret=1
        [[ "$ret" -eq 1 ]] && echo "$(date '+%Y-%m-%d %H:%M:%S')" Network connected. && return 1
    done
}

function wait_until_off {
    ret=0
    while true; do
        sleep 1
        ping -c 3 -i 0.2 -W 2 archlinux.org &> /dev/null || ret=1
        [[ "$ret" -eq 1 ]] && echo "$(date '+%Y-%m-%d %H:%M:%S')" Network disconnected. && return 1
    done
}

while true; do
    wait_until_off
    reset_nm
    wait_until_on
done

