#!/bin/bash

ls /dev/video0 2> /dev/null && echo hey || exit
mkdir "$HOME"/codes/sentinel/data/"$(date '+%Y-%m-%d')"
ffmpeg -f video4linux2 -s 640x360 -i /dev/video0 -ss 0:0:3 -frames:v 1 "$HOME"/codes/sentinel/data/"$(date '+%Y-%m-%d')"/"$(date '+%H:%M:%S')".jpg
