#!/bin/bash

[[ -z $1 ]] && exit
mkdir "$1"
for file in *; do
    trimmed_file=$(echo "$file" | cut -d '-' -f2- | sed 's/^ *//g')
    ffmpeg -i "$file" -c copy -metadata album="$1"  "$1"/"$trimmed_file"

done
