#!/bin/bash

audio_card=$(pactl list short cards | grep _1f | awk  '{print $2}')
case "$1" in
    tv)
        setmonitors
        "$HOME"/codes/bin/setbg
        #echo 'Xft.dpi:   192' | xrdb
        ;;
    outroff|-o|--oo)
        setmonitors mo
        "$HOME"/codes/bin/setbg
        #echo 'Xft.dpi:   96' | xrdb
        ;;
    *)
        setmonitors
        "$HOME"/codes/bin/setbg
        #echo 'Xft.dpi:   96' | xrdb
esac
