#!/bin/bash
layout=$(setxkbmap -query | grep layout | awk '{print $2}')
([ "$layout" == "br" ] && setxkbmap ru && xmodmap ~/.Xmodmap_ru) || ( setxkbmap br && xmodmap ~/.Xmodmap_br) || 
sh -c "xset r rate 300 40"
