#!/bin/bash
WINDOW_ID=$(getwindowid)

case "$1" in
    f|-f)
        path=$(find . -name "$(echo "$2" | awk -F':' '{print $1}')" | head -n 1)
        shift
        ;;
    wf|-wf)
        path=$(find . -wholename "$(echo "$2" | awk -F':' '{print $1}')" | head -n 1)
        shift
        ;;
    igg|-igg)
        path_line=$(git grep -irn "$(echo "$2" | awk -F':' '{print $1}')" | head -n 1)
        path=$(echo "$path_line" | awk -F':' '{print $1}')
        line=$(echo "$path_line" | awk -F':' '{print $2}')
        shift
        ;;
    fzf|-fzf)
        path=$(fzf)
        shift
        ;;
    agg|-agg)
        # n_path_lines=$(git grep -rn -m 1 "$(echo "$2" | awk -F':' '{print $1}')" | wc -l)
        n_path_lines=$(git grep -rn -m 1 "$2" | wc -l)
        for ((i=1; i<= "$n_path_lines"; i++)); do
            echo hmm "$i" "$2"
            tv ngge "$i" "$2"
        done
        shift
        ;;
    gg|-gg)
        path_line=$(git grep -rn "$2" | head -n 1)
        path=$(echo "$path_line" | awk -F':' '{print $1}')
        line=$(echo "$path_line" | awk -F':' '{print $2}')
        shift
        ;;
    ngge|-ngge)
        [ -z "$3" ] && exit
        path_line=$(git grep -rn -m 1 "$3" | head -n "$2" | tail -n 1)
        path=$(echo "$path_line" | awk -F':' '{print $1}')
        line=$(echo "$path_line" | awk -F':' '{print $2}')
        shift
        ;;
    ngg|-ngg)
        [ -z "$3" ] && exit
        path_line=$(git grep -rn "$(echo "$3" | awk -F':' '{print $1}')" | head -n "$2" | tail -n 1)
        path=$(echo "$path_line" | awk -F':' '{print $1}')
        line=$(echo "$path_line" | awk -F':' '{print $2}')
        shift
        ;;
    *)
        path=$(echo "$1" | awk -F':' '{print $1}')
        ;;
esac

[ -z "$line" ] && line=$(echo "$1" | awk -F':' '{print $2}')

if [ -f "${path#a*/}" ] && [ ! -f "$path" ]; then
    path="${path#a*/}"
fi
[ -f "$path" ] && nvr --remote +"$line" --servername /tmp/"$WINDOW_ID" -- "$path" && echo OPENED IN VSS: "$path":"$line"
#[ -f "$path" ] && nvim --server /tmp/"$WINDOW_ID" --remote-send ":e ""$path""<CR>:""$line"":<CR>" && echo OPENED IN VSS: "$path":"$line"
