#!/bin/bash
WINDOW_ID=$(bspc query -N -n)

case "$1" in
    f|-f)
        path=$(find . -name "$(echo "$2" | awk -F':' '{print $1}')" | head -n 1)
        shift
        ;;
    wf|-wf)
        path=$(find . -wholename "$(echo "$2" | awk -F':' '{print $1}')" | head -n 1)
        shift
        ;;
    *)
        path=$(echo "$1" | awk -F':' '{print $1}')
        ;;
esac

line=$(echo "$1" | awk -F':' '{print $2}')

if [ -f "${path#a*/}" ] && [ ! -f "$path" ]; then
    path="${path#a*/}"
fi
[ -f "$path" ] && vim --servername "$WINDOW_ID" --remote-tab +"$line" "$path" && echo OPENED IN VSS: "$path" "$line"

