#!/bin/bash

mount_path="$1"
[ -z "$mount_path" ] && exit

sudo mount  "$mount_path" /mnt/usb/
sudo rsync -uvrP --include='*/' --exclude='/*' "$HOME"/music/spotdl/ /mnt/usb/BlackBerry/music/

sudo umount /mnt/usb/
